-- Generated by scripts/import-problem-pack.mjs
-- Source: data/problem-packs/march-2026.json
BEGIN;

-- 2026-03-01 :: C1
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C1', 'IMO Shortlist 2023 Combinatorics C1', 'Solve IMO Shortlist 2023 C1. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C1)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C1'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C1')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-01', id, TRUE
FROM problems WHERE code = 'C1'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-02 :: C2
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C2', 'IMO Shortlist 2023 Combinatorics C2', 'Solve IMO Shortlist 2023 C2. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C2)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C2'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C2')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-02', id, TRUE
FROM problems WHERE code = 'C2'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-03 :: C3
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C3', 'IMO Shortlist 2023 Combinatorics C3', 'Solve IMO Shortlist 2023 C3. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C3)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C3'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C3')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-03', id, TRUE
FROM problems WHERE code = 'C3'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-04 :: C4
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C4', 'IMO Shortlist 2023 Combinatorics C4', 'Solve IMO Shortlist 2023 C4. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C4)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C4'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C4')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-04', id, TRUE
FROM problems WHERE code = 'C4'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-05 :: C5
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C5', 'IMO Shortlist 2023 Combinatorics C5', 'Solve IMO Shortlist 2023 C5. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C5)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C5'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C5')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-05', id, TRUE
FROM problems WHERE code = 'C5'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-06 :: C6
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C6', 'IMO Shortlist 2023 Combinatorics C6', 'Solve IMO Shortlist 2023 C6. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C6)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C6'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C6')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-06', id, TRUE
FROM problems WHERE code = 'C6'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-07 :: C7
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C7', 'IMO Shortlist 2023 Combinatorics C7', 'Solve IMO Shortlist 2023 C7. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C7)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C7'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C7')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-07', id, TRUE
FROM problems WHERE code = 'C7'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-08 :: C8
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('C8', 'IMO Shortlist 2023 Combinatorics C8', 'Solve IMO Shortlist 2023 C8. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Combinatorics (C8)', 'Combinatorics', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'C8'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'C8')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-08', id, TRUE
FROM problems WHERE code = 'C8'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-09 :: N1
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N1', 'IMO Shortlist 2023 Number Theory N1', 'Solve IMO Shortlist 2023 N1. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N1)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N1'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N1')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-09', id, TRUE
FROM problems WHERE code = 'N1'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-10 :: N2
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N2', 'IMO Shortlist 2023 Number Theory N2', 'Solve IMO Shortlist 2023 N2. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N2)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N2'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N2')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-10', id, TRUE
FROM problems WHERE code = 'N2'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-11 :: N3
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N3', 'IMO Shortlist 2023 Number Theory N3', 'Solve IMO Shortlist 2023 N3. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N3)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N3'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N3')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-11', id, TRUE
FROM problems WHERE code = 'N3'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-12 :: N4
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N4', 'IMO Shortlist 2023 Number Theory N4', 'Solve IMO Shortlist 2023 N4. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N4)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N4'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N4')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-12', id, TRUE
FROM problems WHERE code = 'N4'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-13 :: N5
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N5', 'IMO Shortlist 2023 Number Theory N5', 'Solve IMO Shortlist 2023 N5. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N5)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N5'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N5')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-13', id, TRUE
FROM problems WHERE code = 'N5'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-14 :: N6
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N6', 'IMO Shortlist 2023 Number Theory N6', 'Solve IMO Shortlist 2023 N6. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N6)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N6'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N6')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-14', id, TRUE
FROM problems WHERE code = 'N6'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-15 :: N7
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N7', 'IMO Shortlist 2023 Number Theory N7', 'Solve IMO Shortlist 2023 N7. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N7)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N7'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N7')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-15', id, TRUE
FROM problems WHERE code = 'N7'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-16 :: N8
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('N8', 'IMO Shortlist 2023 Number Theory N8', 'Solve IMO Shortlist 2023 N8. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Number Theory (N8)', 'Number Theory', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'N8'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'N8')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-16', id, TRUE
FROM problems WHERE code = 'N8'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-17 :: A1
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A1', 'IMO Shortlist 2023 Algebra A1', 'Solve IMO Shortlist 2023 A1. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A1)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A1'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A1')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-17', id, TRUE
FROM problems WHERE code = 'A1'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-18 :: A2
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A2', 'IMO Shortlist 2023 Algebra A2', 'Solve IMO Shortlist 2023 A2. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A2)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A2'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A2')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-18', id, TRUE
FROM problems WHERE code = 'A2'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-19 :: A3
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A3', 'IMO Shortlist 2023 Algebra A3', 'Solve IMO Shortlist 2023 A3. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A3)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A3'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A3')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-19', id, TRUE
FROM problems WHERE code = 'A3'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-20 :: A4
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A4', 'IMO Shortlist 2023 Algebra A4', 'Solve IMO Shortlist 2023 A4. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A4)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A4'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A4')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-20', id, TRUE
FROM problems WHERE code = 'A4'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-21 :: A5
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A5', 'IMO Shortlist 2023 Algebra A5', 'Solve IMO Shortlist 2023 A5. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A5)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A5'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A5')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-21', id, TRUE
FROM problems WHERE code = 'A5'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-22 :: A6
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A6', 'IMO Shortlist 2023 Algebra A6', 'Solve IMO Shortlist 2023 A6. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A6)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A6'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A6')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-22', id, TRUE
FROM problems WHERE code = 'A6'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-23 :: A7
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A7', 'IMO Shortlist 2023 Algebra A7', 'Solve IMO Shortlist 2023 A7. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A7)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A7'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A7')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-23', id, TRUE
FROM problems WHERE code = 'A7'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-24 :: A8
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('A8', 'IMO Shortlist 2023 Algebra A8', 'Solve IMO Shortlist 2023 A8. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Algebra (A8)', 'Algebra', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'A8'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'A8')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-24', id, TRUE
FROM problems WHERE code = 'A8'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-25 :: G1
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G1', 'IMO Shortlist 2023 Geometry G1', 'Solve IMO Shortlist 2023 G1. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G1)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G1'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G1')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-25', id, TRUE
FROM problems WHERE code = 'G1'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-26 :: G2
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G2', 'IMO Shortlist 2023 Geometry G2', 'Solve IMO Shortlist 2023 G2. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G2)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G2'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G2')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-26', id, TRUE
FROM problems WHERE code = 'G2'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-27 :: G3
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G3', 'IMO Shortlist 2023 Geometry G3', 'Solve IMO Shortlist 2023 G3. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G3)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G3'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G3')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-27', id, TRUE
FROM problems WHERE code = 'G3'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-28 :: G4
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G4', 'IMO Shortlist 2023 Geometry G4', 'Solve IMO Shortlist 2023 G4. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G4)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G4'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G4')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-28', id, TRUE
FROM problems WHERE code = 'G4'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-29 :: G5
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G5', 'IMO Shortlist 2023 Geometry G5', 'Solve IMO Shortlist 2023 G5. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G5)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G5'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G5')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-29', id, TRUE
FROM problems WHERE code = 'G5'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-30 :: G6
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G6', 'IMO Shortlist 2023 Geometry G6', 'Solve IMO Shortlist 2023 G6. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G6)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G6'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G6')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-30', id, TRUE
FROM problems WHERE code = 'G6'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

-- 2026-03-31 :: G7
INSERT INTO problems (code, title, statement_md, source, topic, answer_spec)
VALUES ('G7', 'IMO Shortlist 2023 Geometry G7', 'Solve IMO Shortlist 2023 G7. Write a full proof-based solution with clear claims and justification.', 'IMO Shortlist 2023, Geometry (G7)', 'Geometry', '{"mode":"proof","check_strategy":"rubric-guided"}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  statement_md = EXCLUDED.statement_md,
  source = EXCLUDED.source,
  topic = EXCLUDED.topic,
  answer_spec = EXCLUDED.answer_spec;
INSERT INTO problem_rubrics (problem_id, version, max_points, criteria, hint_policy, is_active)
SELECT id, 1, 7, '[{"id":"setup","label":"Key setup and useful observations","max_points":2},{"id":"argument","label":"Logical progression and valid proof steps","max_points":3},{"id":"conclusion","label":"Correct conclusion and edge-case handling","max_points":2}]'::jsonb, '{"max_hints":3,"allow_final_answer":false,"allow_full_proof":false}'::jsonb, TRUE
FROM problems WHERE code = 'G7'
ON CONFLICT (problem_id, version) DO UPDATE SET
  max_points = EXCLUDED.max_points,
  criteria = EXCLUDED.criteria,
  hint_policy = EXCLUDED.hint_policy,
  is_active = TRUE,
  updated_at = NOW();
UPDATE problem_rubrics
SET is_active = FALSE, updated_at = NOW()
WHERE problem_id = (SELECT id FROM problems WHERE code = 'G7')
  AND version <> 1;
INSERT INTO problem_schedule (local_date, problem_id, published)
SELECT DATE '2026-03-31', id, TRUE
FROM problems WHERE code = 'G7'
ON CONFLICT (local_date) DO UPDATE SET
  problem_id = EXCLUDED.problem_id,
  published = EXCLUDED.published,
  updated_at = NOW();

COMMIT;
